version: '3.8'

services:
  postgres-summary:
    image: postgres:15
    container_name: pg_summary
    environment:
      POSTGRES_DB: pg_summary_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
